// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udrcbsvcgstutmkghawb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkcmNic3ZjZ3N0dXRta2doYXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMDcwNzksImV4cCI6MjA1NDU4MzA3OX0.inPNoVkPstLqPIjNZI_XZ95QH7JGvOovs1kPHMXg_Dw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);